# Upstream changes from _extends are only recognized when modifications are made to this file in the default branch.
_extends: .github
repository:
  name: terraform-aws-glue
  description: Terraform modules for provisioning and managing AWS Glue resources
  homepage: https://cloudposse.com/accelerate
  topics: aws, aws-glue, etl, etl-job, glue, workflow

